FROM debian:testing-slim

RUN apt-get update && apt-get upgrade -y && apt-get install -y \
    make \
    pipx \
    python3-full \
    python3-pip \
    python3-requests \
    python3-tqdm \
    ;

RUN useradd zidel
RUN mkdir /home/zidel
RUN chown zidel:zidel -R /home/zidel
USER zidel
WORKDIR /home/zidel

ENV PATH=/home/zidel/.venv/bin:$PATH
RUN python3 -m venv .venv
RUN pip install tensorflow
